baseURL = "https://lapjo.com/"
languageCode = "en-us"
theme = ["hugo-winston-theme", "hugo-shortcodes"]
themesDir = "themes"
title = "Lapjo"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = false

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = "G-GBMEKXV6WC"
  twitter_handle = "@okelloj3"
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = true
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 4 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  # addDot = true
  addFrame = true
  highlightColor = '#7fcc28'
  baseColor = "#232323"
  baseOffsetColor = "#ebdbb2"
  headingColor = "#fabd27"
  textColor = "#f0f0f0"
  dotColor = "#fe8019"
  enableGoogleFonts = true 
  googleFontsUrl = "https://fonts.bunny.net/css2?family=Poppins:wght@400;700&display=swap"
  fontFamilyHeading = "Poppins"
  fontFamilyParagraph = "Helvetica"
  fontFamilyMonospace = "monospace"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
    [markup.highlight]
      anchorLineNos = false
      codeFences = true
      guessSyntax = true
      hl_Lines = ''
      hl_inline = false
      lineAnchors = ''
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = true
      noClasses = true
      noHl = false
      style = 'gruvbox dark'

[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 2
    url = "/posts/"
  [[menu.main]]
    name = "About"
    identifier = "about"
    weight = 3
    url = "/pages/about/"
  [[menu.main]]
    name = "Tags"
    identifier = "tags"
    weight = 4
    url = "/tags/"
